import fs from 'fs';

console.log(`generating temp/common/stringTypeToMessageType.mjs`);

import h2c from '../common/hyphen2camel.mjs';
import validators from '../common/messageTypes.mjs';

let js = '';

js += `// ! This file is generated automatically. Do not edit this file!\n`
js += `import * as MessageTypes from './MessageTypes.mjs';\n`;
js += `export default {\n`;

for (let messageType in validators) {
  js += `    '${messageType}':\n        MessageTypes.${h2c(messageType)},\n`;
}

js += `}`;

fs.writeFileSync(`temp/common/stringTypeToMessageType.mjs`, js); // assuming script run from root of project
