#! /bin/bash

rm -r dist-client > /dev/null
mkdir dist-client

rm -r temp > /dev/null

cp -r src/ temp

# code generators
node --experimental-modules \
  ./temp/generators/gen__MessageTypes_mjs.mjs
node --experimental-modules \
  ./temp/generators/gen__messageTypeToStringType_mjs.mjs
node --experimental-modules \
  ./temp/generators/gen__stringTypeToMessageType_mjs.mjs

cp ./temp/client/html/*.html ./dist-client/
cp ./temp/client/css/*.css ./dist-client/

rollup ./temp/client/index.mjs \
  --format iife \
  --file ./dist-client/game.js

rm -r temp
